<?php
return [
    'amazonia' => [
        'nome' => 'Ciclus Amazônia',
        'logo' => 'assets/amazonia/btn.png',
        'base' => 'assets/amazonia/base.png',
        'fonte' => './fonts/HelveticaNeue.ttc',
        'cor' => '#3b6533',
        'cor_telefone' => '#3b6533',
        'endereco' => 'R. Jardim da Providência, 09 – Águas Lindas, Ananindeua – PA',
        'site' => 'https://ciclusamazonia.com.br/',
    ],
    'rio' => [
        'nome' => 'Ciclus Rio',
        'logo' => 'assets/rio/btn.png',
        'base' => 'assets/rio/base.png',
        'fonte' => './fonts/HelveticaNeue.ttc',
        'cor' => '#43808e',
        'cor_telefone' => '#43808e',
        'endereco' => 'Arco Metropolitano, KM 107 – Seropédica, RJ',
        'site' => 'https://ciclusrio.com.br/',
    ],
    'ambiental' => [
        'nome' => 'Ciclus Ambiental',
        'logo' => 'assets/ambiental/btn.png',
        'base' => 'assets/ambiental/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
        'endereco' => 'Rua Doutor Renato Paes de Barros, nº 1.017, 8º andar - São Paulo/SP',
        'site' => 'https://ciclusambiental.com.br/',
    ],
    'graos' => [
        'nome' => 'CS Graos do Piauí',
        'logo' => 'assets/graos/btn.png',
        'base' => 'assets/graos/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
        'endereco' => 'Rodovia BR 135 km 148- Edifício DAYTOP – Zona Rural, Bom Jesus, PI',
        'site' => 'https://csgraosdopiaui.com.br/',
    ],
    'infra' => [
        'nome' => 'CS Infra',
        'logo' => 'assets/infra/btn.png',
        'base' => 'assets/infra/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
        'endereco' => 'Rua Doutor Renato Paes de Barros, nº 1.017, 8º andar - São Paulo/SP',
        'site' => 'https://csinfra.com.br/',
    ],
    'mobi' => [
        'nome' => 'CS Mobi Cuiabá',
        'logo' => 'assets/mobi/btn.png',
        'base' => 'assets/mobi/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
        'endereco' => 'Avenida Isaac Póvoas, 560 - Bairro Goiabeiras – Cuiabá/MT',
        'site' => 'https://csmobicuiaba.com.br/',
    ],
    'portos' => [
        'nome' => 'Empresa CS Portos',
        'logo' => 'assets/portos/btn.png',
        'base' => 'assets/portos/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
        'endereco' => 'Rodovia Matoim, S/N – Porto de Aratu - Candeias-Ba /',
        'site' => 'https://csportoaratu.com.br/',
    ],
];
