<?php
return [
    'amazonia' => [
        'nome' => 'Ciclus Amazônia',
        'logo' => 'assets/amazonia/btn.png',
        'base' => 'assets/amazonia/base.png',
        'fonte' => './fonts/HelveticaNeue.ttc',
        'cor' => '#3b6533',
        'cor_telefone' => '#3b6533',
    ],
    'rio' => [
        'nome' => 'Ciclus Rio',
        'logo' => 'assets/rio/btn.png',
        'base' => 'assets/rio/base.png',
        'fonte' => './fonts/HelveticaNeue.ttc',
        'cor' => '#43808e',
        'cor_telefone' => '#43808e',
    ],
    'ambiental' => [
        'nome' => 'Ciclus Ambiental',
        'logo' => 'assets/ambiental/btn.png',
        'base' => 'assets/ambiental/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
    ],
    'graos' => [
        'nome' => 'CS Graos do Piauí',
        'logo' => 'assets/graos/btn.png',
        'base' => 'assets/graos/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
    ],
    'infra' => [
        'nome' => 'CS Infra',
        'logo' => 'assets/infra/btn.png',
        'base' => 'assets/infra/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
    ],
    'mobi' => [
        'nome' => 'CS Mobi Cuiabá',
        'logo' => 'assets/mobi/btn.png',
        'base' => 'assets/mobi/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
    ],
    'portos' => [
        'nome' => 'Empresa CS Portos',
        'logo' => 'assets/portos/btn.png',
        'base' => 'assets/portos/base.png',
        'fonte' => './fonts/intelo/Intelo-Regular.ttf',
        'cor' => '#424893',
        'cor_telefone' => '#d57c31',
    ],
];
